- modules/common/src/test/java/com/ibm/cloud/cloudant/security/CouchDbSessionTokenTest.java
Correct exceptions thrown by test code, see:
https://github.com/IBM/cloudant-java-sdk/pull/52#discussion_r539243404
https://github.com/IBM/cloudant-java-sdk/pull/52#discussion_r539246413
- [x The commit message follows the
`needsRefresh()` test declares `Exception` which is more broad than the `InterruptedException` needed.
`refreshTimeCalculation()` test declares that it throws `Exception` unnecessarily.
`needsRefresh()` - `throws InterruptedException`.
`refreshTimeCalculation()` - removed `throws` declaration.
@vmatyusGitHub I felt it was worth still correcting these test issues that were …
> Correct CouchDbSessionTokenTest declared exceptions

- build/.travis.settings.xml
- modules/coverage-reports/pom.xml
- pom.xml
Maven changes to deploy to Maven central/sonatype instead of bintray.
Release deployment is currently to Bintray with a later sync to Maven Central.
Release deployment is to Maven Central.
* `bintray` profile is replaced by `central` profile with sonatype plugin configuration
* Coverage reports are skipped from deployment
* Signing by inclusion and configuration of `org.kohsuke:pgp-maven-plugin:1.1`
* Additional `skipunits` profile to keep `-DskipTests` working with new `skip.unit.tests` option from template updates.
The enablement of the `signing` profile is toggled by the presence of the …
> Publish to Maven central

- modules/examples/pom.xml
- pom.xml
Update module ordering so that deployment isn't skipped
Fixes: #109 (for future releases)
Deployment was skipped because the code-coverage report (that intentionally skips deployment) was the last module listed and so skipped the batched deployment of other resources.
Enable javadoc generation for the `cloudant-examples` module and list that last so that all the batched modules get deployed.
> 303 maven central pt2

- pom.xml
This PR adds configuration for `maven-checkstyle-plugin` to use `checkstyle` version 9.0.1 (latest atm) instead of default 8.29
Fixes: #177 
Old `checkstyle` used leading to upgrade warnings during the tests.
New `checkstyle` used with warnings gone
> Change maven-checkstyle-plugin to use checkstyle version 9.0.1

- modules/common/src/main/java/com/ibm/cloud/cloudant/internal/DelegatingAuthenticatorFactory.java
- modules/common/src/test/java/com/ibm/cloud/cloudant/internal/DelegatingAuthenticatorFactoryTest.java
Support a env var name alias `AUTHTYPE` for `AUTH_TYPE` to keep core's compatibility
Env var of format `SERVICE_AUTHTYPE` is ignored and error thrown on missing required variable
Env var of format `SERVICE_AUTHTYPE` accepted as a valid variable same as `SERVICE_AUTH_TYPE`
> Support alias env var AUTHTYPE

- modules/common/src/main/java/com/ibm/cloud/cloudant/internal/DelegatingAuthenticatorFactory.java
- modules/common/src/test/java/com/ibm/cloud/cloudant/internal/DelegatingAuthenticatorFactoryTest.java
This will allow other libraries eg spring/kafka to easily configure a cloudant service instance with different authentication methods from their configuration sources.
> Use `serviceProperties` map in 2nd getAuthenticator overload

- pom.xml
- Remove obsolete footer option
- Fix organization. This affects the default `-bottom` option for
javadoc to produce something like
"Copyright © 2022 IBM Corporation. All rights reserved."
> Fix javadoc:

- modules/common/src/main/java/com/ibm/cloud/cloudant/internal/CloudantBaseService.java
- modules/common/src/test/java/com/ibm/cloud/cloudant/internal/ValidationTest.java
add missing operation names to path validator
Not all operations have paths validated
Validate paths additionally on
`getDocumentAsMixed`
`getDocumentAsRelated`
`getDocumentAsStream`
migration path: any applications which use special paths for the above operations should use the correct operation, eg one of the `*AllDocs*` methods in the case of the `_all_docs` path.
> fix: add missing operation names to path validator

- .github/workflows/test.yml
- pom.xml
Fixes: #369 
We currently run tests against Java 8, 11, and 17 with GH actions.  The test suite requires `testng` and `mockito` packages.  The latest version of both of these packages supports Java 11 and greater.  For us to upgrade, we need to remove Java 8 from the GHA matrix.
Remove Java 8 from GH actions.
> Remove Java 8 in GH actions

- .github/workflows/docs.yml
To ensure that we have docs builder working correctly this PR adds a github action that'd run docs build command on pull requests against `main`.
We don't care about difference with `gh-pages` content, so the test is only about ability to successfully run the docs build command itself.
> ci: add github action to test docs builder

- .whitesource
chore: use Java 17 for scans
Scanner uses default Java version.
Scanner uses Java version 17.
> chore: use Java 17 for scans

- scripts/javadoc/publish-doc.sh
fixes #512 
Javadoc displays `features` on main page.
Javadoc does not display `features` on main page.
I tested this locally and now I cannot see it:
> build(javadoc): skip examples module from Javadoc

- modules/examples/pom.xml
This reverts commit a5f780d8499cb8d4a63253981df9a4dd5f9c78fa.
Javadoc skip prevents publication of examples module.
Reverting the commit creates javadoc for the examples module again.
> Revert "build: skip javadoc generation for examples module"

- modules/examples/pom.xml
Disable `javadoc` warnings for examples module.
> build: disable javadoc warnings for examples module

- pom.xml
In our Javadoc we can't follow links to the `java-sdk-core` (e.g. `ServiceCall`) from here:
https://ibm.github.io/cloudant-java-sdk/docs/0.9.1/com/ibm/cloud/cloudant/v1/Cloudant.html#getSessionInformation()
This PR configures the links maven parameter to `https://ibm.github.io/java-sdk-core/docs/${sdk-core-version}`.
^ this link directs me to https://ibm.github.io/java-sdk-core/docs/9.21.1/com/ibm/cloud/sdk/core/http/ServiceCall.html?is-external=true
> docs: fix javadoc cross-linking to sdk-core

- modules/common/src/main/java/com/ibm/cloud/cloudant/internal/CloudantBaseService.java
- modules/common/src/main/java/com/ibm/cloud/cloudant/security/CouchDbSessionAuthenticator.java
- modules/common/src/test/java/com/ibm/cloud/cloudant/internal/SdkTimeoutTest.java
- modules/common/src/test/java/com/ibm/cloud/cloudant/security/CouchDbSessionAuthenticatorTest.java
The purpose of this PR was originally calling and returning the result of core's `invokeRequest` from our `requestToken` method, but the [`convert`](https://github.com/IBM/java-sdk-core/blob/f2ed2b1449eefca1c5084e5bfdd5d6988d6ccd3c/src/main/java/com/ibm/cloud/sdk/core/util/ResponseConverterUtils.java#L137) method called in `invokeRequest` takes [variables only from the response body](https://github.com/IBM/java-sdk-core/blob/f2ed2b1449eefca1c5084e5bfdd5d6988d6ccd3c/src/main/java/com/ibm/cloud/sdk/core/util/ResponseUtils.java#L148). With this feature response headers which are essential to `CouchDBSessionAuthenticator` cannot be reverse engineered from `invokeRequest`.
Although I could change `sessionAuthClient` with getter and setter methods introduced in …
> refactor: use setClient and getClient of core

- modules/common/src/test/java/com/ibm/cloud/cloudant/internal/TestCloudantService.java
- modules/common/src/test/java/com/ibm/cloud/cloudant/security/CouchDbSessionAuthenticatorTest.java
Some minor clean ups  in the session tests.
Associated with s681 and #599 
When reviewing  #599 I noticed that some of the test assertion expected/actual were reversed. This gave confusing messages when tests failed.
* Correct the assertion method arg order to give correct messages
* Remove unused import
* `MockWebServer` is a `Closeable` so we can use try-with-resources for a cleaner test
> test: fix assertion order in session tests

- modules/cloudant/src/test/java/com/ibm/cloud/cloudant/v1/CloudantErrorInterceptorTest.java
- modules/common/src/main/java/com/ibm/cloud/cloudant/internal/CloudantBaseService.java
- modules/common/src/main/java/com/ibm/cloud/cloudant/internal/ErrorTransformInterceptor.java
- modules/common/src/test/java/com/ibm/cloud/cloudant/internal/ErrorTransformInterceptorTest.java
Add interceptor for error response augmentation
Fixes: s1002
Cloudant/CouchDB error models are handled by the core with only the `error` field being processed. Obtaining e.g. the `reason` field requires additional user code.
The error response is augmented with `errors` and `trace` properties.
This improves the way the core handles the error response and enhances the user facing exception string to include the `reason`.
The `trace` is the CouchDB request ID which …
> feat: improve error response messages

- modules/common/src/main/java/com/ibm/cloud/cloudant/internal/ErrorTransformInterceptor.java
- modules/common/src/test/java/com/ibm/cloud/cloudant/internal/ErrorTransformInterceptorTest.java
If the `x-request-id` header is on a response use it to set the error `trace` field (in preference to `x-couch-request-id`, but still use `x-couch-request-id` if there is no `x-request-id`).
Fixes: part of s1037
The error `trace` introduced in #614 only handles CouchDB's `x-couch-request-id` header on responses.
The error `trace` also handles `x-request-id` header on responses.
> feat: set x-request-id as error trace

- modules/cloudant/src/main/java/com/ibm/cloud/cloudant/features/ChangesResultSpliterator.java
Assign `since` correctly when initializing `ChangesResultSpliterator`
Fixes: #629
`this.since` is used when copying the options for the request, but `this.since` is only set for the default `null` cases.
Set `this.since` to `this.options.since()` and only then apply the defaults if necessary.
> fix: assign since correctly in changes follower

- .secrets.baseline
- Jenkinsfile
- build/jenkins.settings.xml
- pom.xml
Use the new central portal plugin for Maven publishing.
Fixes: s1171
Publish via OSSRH.
Publish via Central Portal.
Can't really test this without doing actually doing a release.
> Change to central portal publishing

- .github/workflows/static.yml
Update versions of actions in GH pages deployment workflow
Fixes: part of s1192
Actions are not pinned by sha.
Actions are pinned by sha.
> chore: pin gh-pages actions by sha

- modules/cloudant/src/main/java/com/ibm/cloud/cloudant/features/pagination/AllDocsPageIterator.java
- modules/cloudant/src/main/java/com/ibm/cloud/cloudant/features/pagination/AllDocsPartitionPageIterator.java
- modules/cloudant/src/main/java/com/ibm/cloud/cloudant/features/pagination/BasePageIterator.java
- modules/cloudant/src/main/java/com/ibm/cloud/cloudant/features/pagination/DesignDocsPageIterator.java
- modules/cloudant/src/main/java/com/ibm/cloud/cloudant/features/pagination/FindPager.java
- modules/cloudant/src/main/java/com/ibm/cloud/cloudant/features/pagination/FindPartitionPager.java
- modules/cloudant/src/main/java/com/ibm/cloud/cloudant/features/pagination/KeyPageIterator.java
- modules/cloudant/src/main/java/com/ibm/cloud/cloudant/features/pagination/OptionsHandler.java
- modules/cloudant/src/main/java/com/ibm/cloud/cloudant/features/pagination/SearchPageIterator.java
- modules/cloudant/src/main/java/com/ibm/cloud/cloudant/features/pagination/SearchPartitionPageIterator.java
- modules/cloudant/src/main/java/com/ibm/cloud/cloudant/features/pagination/ViewBasePageIterator.java
- modules/cloudant/src/main/java/com/ibm/cloud/cloudant/features/pagination/ViewPageIterator.java
- modules/cloudant/src/main/java/com/ibm/cloud/cloudant/features/pagination/ViewPartitionPageIterator.java
- modules/cloudant/src/test/java/com/ibm/cloud/cloudant/features/pagination/BasePageIteratorTest.java
- modules/cloudant/src/test/java/com/ibm/cloud/cloudant/features/pagination/BookmarkPageIteratorTest.java
- modules/cloudant/src/test/java/com/ibm/cloud/cloudant/features/pagination/KeyPageIteratorTest.java
- modules/cloudant/src/test/java/com/ibm/cloud/cloudant/features/pagination/OptionsValidationTest.java
- modules/cloudant/src/test/java/com/ibm/cloud/cloudant/features/pagination/PaginationTestHelpers.java
Fixes: s1187
The new (unreleased) pagination code delivered in #696 had some bugs.
* Disallow `key` as an option for pagination
* Fix NPEs for reduced/grouped view results with `null` IDs
* Fix page size adjustment for key-based (n+1) pagination
* Remove `skip` option from subsequent pages
* Add new test assertions to check page size against options
* Add new tests for `key` option validation
* Add new tests for asserting `skip` option changes
* Refactor the …
> Miscellaneous pagination fixes

- pom.xml
Temporarily add a direct dependency on commons-lang3 `3.18.0`
Fixes: s1197, s1198, s1199
`org.apache.commons::commons-lang3` `3.17.0` transitively via `com.ibm.cloud::sdk-core`
`org.apache.commons::commons-lang3` `3.18.0` directly to get update ahead of `com.ibm.cloud::sdk-core` `9.24.2` release.
This change should be reverted after `com.ibm.cloud::sdk-core::9.24.2` is available.
> build (deps): org.apache.commons::commons-lang3 to 3.18.0

- pom.xml
Adjust maven publishing wait until condition
Fixes: s1227
Waits up to half an hour for library to publish to Maven Central, polling for state every 5 seconds.
Waits up to an hour for library to validate, polling for state every 15 seconds.
The sync from Central Portal to Maven Central timed out during the last release. Since we always check that the release has reached Maven Central before marking the release process completed anyway we can avoid potential future timeouts by waiting only for the `validated` state. In `validated` state we know the upload is good and meets the requirements of Maven …
> ci: adjust maven publishing wait until condition
