IBM/cloudant-java-sdk

- pom.xml
Fixes: #6 
**Note: An existing issue is [required](https://github.com/IBM/cloudant-node-sdk/blob/master/CONTRIBUTING.md#PRs) before opening a PR.**
Current version of `sdk-core` is `9.0.1`
`sdk-core` is updated to `9.1.0`
> Update sdk core to 9.1.0

- pom.xml
Fixes: #11 
sdk core version is 9.1.0
core version updated to 9.1.1
> Update sdk core to 9.1.1

- modules/cloudant/pom.xml
- modules/common/pom.xml
- modules/common/src/main/java/com/ibm/cloud/cloudant/common/SdkCommon.java
- modules/common/src/test/java/com/ibm/cloud/cloudant/SdkCommonTest.java
- modules/common/src/test/java/com/ibm/cloud/cloudant/internal/DelegatingAuthenticatorFactoryTest.java
- modules/common/src/test/java/com/ibm/cloud/cloudant/security/CouchDbSessionAuthenticatorTest.java
- modules/common/src/test/java/com/ibm/cloud/cloudant/security/CouchDbSessionTokenTest.java
> Add operation ID to headers

- pom.xml
* IAM Authenticator: add support for optional 'scope' property
* iam/cp4d token refresh logic
* resolve path params by name, not by parameter ordering
> Update core version to 9.3.0

- pom.xml
`sdk-core-version` is at version 9.3.0
`sdk-core-version` updated to 9.4.0
https://github.com/IBM/java-sdk-core/releases/tag/9.4.0
> Update core dependency to 9.4.1

- .travis.yml
Enable codecov.io code coverage. Disabled uploading to s3 remote target and running python coverage functions.
Default configuration: https://docs.codecov.io/docs/codecov-yaml#default-yaml
> Enable codecov.io

- README.md
- modules/examples/src/main/java/GetInfoFromExistingDatabase.java
Change var name in `GetInfoFromExistingDatabase.java` and README examples from `examplesClient` to `client` for consistency with the rest of the examples.
> docs: Update var name in GetInfoFromExistingDatabase example

- README.md
Add a section about error handling.
Link Cloudant API docs error handling section.
**Note**: The referred link content will be visible only for those who has Cloud subscription.
No behaviour change.
> Add error handling section to README.md

- pom.xml
Gather dependabot PRs into one PR.
This PR has all the commits from dependabot PRs:
* https://github.com/IBM/cloudant-java-sdk/pull/38 -> powermock-version
* https://github.com/IBM/cloudant-java-sdk/pull/37 -> maven-source-plugin
* https://github.com/IBM/cloudant-java-sdk/pull/36 -> slf4-jdk14
* https://github.com/IBM/cloudant-java-sdk/pull/35 -> testng
* https://github.com/IBM/cloudant-java-sdk/pull/34 -> maven-site-plugin
This PR bumps the dependencies to the versions mentioned in the commit messsages.
> Dependabot cherry pick

- modules/cloudant/pom.xml
- pom.xml
Gather dependabot PRs into one PR.
This PR has all the commits from dependabot PRs:
* https://github.com/IBM/cloudant-java-sdk/pull/41 -> sdk-core
* https://github.com/IBM/cloudant-java-sdk/pull/42 -> maven-checkstyle-plugin
* https://github.com/IBM/cloudant-java-sdk/pull/43 -> jacoco-maven-plugin
* https://github.com/IBM/cloudant-java-sdk/pull/44 -> gson
* https://github.com/IBM/cloudant-java-sdk/pull/45 -> maven-project-info-plugin
This PR bumps the dependencies to the versions mentioned in the commit messsages.
> Dependabot cherry-pick 2

- .github/CODEOWNERS
Fixes: https://github.com/IBM/cloudant-java-sdk/pull/47/files#r528754142 and https://github.com/IBM/cloudant-java-sdk/pull/47/files#r528755420
By mistake, I merged the previous PR (#47) without the suggested modifications.
Now the suggestions are applied.
> Fix Init codeowners

- checkstyle.xml
- config/java.header
The header checks right now are using exact text matches which is not flexible.
This commit refactors that check into a regex check so that it becomes more flexible.
See above.
See above.
> Switch header checks to regex

- checkstyle-suppressions.xml
- config/java.header
Generated files are excluded from `checkstyle` header checks. This PR includes them so that they are verified.
> Add header checks for generated files

- modules/common/src/main/java/com/ibm/cloud/cloudant/common/package-info.java
- modules/common/src/main/java/com/ibm/cloud/cloudant/security/CouchDbSessionAuthenticator.java
Fixes: #65
Broken links were in the javadoc.
Replaced them with `service client` to be future proof if we are going to add other kinds of services to this package (e.g. TXE). This way we do not have to rewrite them again.
> Remove com.ibm.cloud.cloudant.Cloudant links

- KNOWN_ISSUES.md
Add details about disabling gzip compression for session auth and a code example to KNOWN_ISSUES.
> Update KNOWN_ISSUES with session auth section

- .travis.yml
Currently we are not getting any benefit from the `codecov` integration and  due to [a recent security incident](https://about.codecov.io/security-update/?utm_medium=email&utm_source=marketo&ajs_uid=&ajs_event=Clicked%20Email&mkt_tok=MzMyLUxWWC03NDEAAAF8dJnGkNG_ojrjdXL2M-fOtB8t5IIphrIeLMth6mxIfuhPHB7b_FDof-GXtPcIc5fc754EGZ-_sxnLPdyBwLd1yNBoppIr0iZuG9A5_FAL) we decided to remove it.
> ci: remove codecov install and execution

- KNOWN_ISSUES.md
With #116 there will be no need for this sentence.
> docs(KNOWN_ISSUES.md): remove open revs note

- modules/examples/src/main/java/UpdateDoc.java
Fixes: <! -- link to issue -->
Add stream handling examples in note comments to update document example.
> Add streaming example file

- pom.xml
Fixes: #13 
Using workaround to build javadoc for JDK 9+.
Workaround does not need anymore.
> Remove profile with workaround for javadoc

- modules/common/src/test/java/com/ibm/cloud/cloudant/security/CouchDbSessionTokenTest.java
Fixes: https://app.travis-ci.com/github/IBM/cloudant-java-sdk/jobs/536611764
Fix current test case.
`refreshTimeCalculation` test is failing due to the expected and the actual assertion values are swapped + there is no delta set.
I set a `1.0` delta & changed the assertion value order.
> test(couchdbSessionToken): Fix refresh time calculation assertion

- .travis.yml
- pom.xml
Relates to: #114 
Java Open JDK 14 is supported
Java Open JDK 14 is now removed and 16 introduced.
> Update latest test version from 14 to 17.

- .secrets.baseline
This PR adds a `.secret.baseline` file for `detect-secrets`.
No secrets detect is used.
Add `secrets.baseline` file that excludes:
- stubs/+.json files
> add secrets baseline

- KNOWN_ISSUES.md
CouchDB 3.2.0 contains the fix for gzipped `_session` requests.
Updated the minimum CouchDB version in the session auth statement.
> Update session auth statement in README

- pom.xml
This reverts commit 91816595909475e0673f23c2d57cc653cf98f409.
Related to https://issues.sonatype.org/browse/OSSRH-66257
> build(deps): revert bump nexus-staging-maven-plugin from 1.6.8 to 1.6.10

- modules/common/src/main/java/com/ibm/cloud/cloudant/common/SdkCommon.java
Fixes: <! -- link to issue -->
`user-agent` header can sometimes overflow 64 chars.
Use new commonly agreed format for `user-agent` header, truncating some parts where necessary.
- [] Yes
> Use common format for user-agent header

- .secrets.baseline
- .travis.yml
- modules/examples/src/main/java/CreateDbAndDoc.java
- modules/examples/src/main/java/DeleteDoc.java
- modules/examples/src/main/java/GetInfoFromExistingDatabase.java
- modules/examples/src/main/java/UpdateDoc.java
The goal of this PR is to improve the description of `_rev`/`rev` requirements for post/put document. I also tried to explain where `_id`/`docId` is necessary similarly to `_rev`/`rev`.
I decided to use `/*...code is here...*/` for code comments and ornamentation lines before and after the explanation plus the commented out codes because with this way maybe the eyes can catch what belongs to what. 
I also fixed the indentation for the examples and removed the unused `documentInfoOptions` variable in `modules/examples/src/main/java/CreateDbAndDoc.java`.
Explanation in example code how to use …
> docs: improve description of rev requirements for post/put document

- KNOWN_ISSUES.md
Documentation change: remove IAM/reflective access section.
This has since been fixed in the SDK core and no longer applies.
> 428: Remove IAM/reflective access section

- .github/workflows/test.yml
Disable persisting the actions token
`persist-credentials: true` the default for checkout action
`persist-credentials: false`
The actions don't need to run any other `git` commands.
> Disable persisting the actions token

- modules/examples/output/GetInfoFromExistingDatabase.txt
- modules/examples/src/main/java/GetInfoFromExistingDatabase.java
Update get_info examples to remove refs to deprecated examples.cloudant.com
> docs: update get_info examples

- modules/common/src/main/java/com/ibm/cloud/cloudant/security/CouchDbSessionAuthenticator.java
- modules/common/src/test/java/com/ibm/cloud/cloudant/internal/SdkTimeoutTest.java
Fixes: _Child class fields should not shadow parent class fields_
> fix: child class fields should not shadow parent class fields

- .github/workflows/static.yml
Use GHA to deploy to pages.
Classic pages deployment.
GitHub Actions pages deployment.
The classic deployment no longer supports symlinks, changing to actions will hopefully avoid the need to rework the way we link latest to the most recent tagged version.
> ci: javadoc pages deployment action

- .secrets.baseline
- Jenkinsfile
- pom.xml
Switch from old signing with GPG key to CISO signing solution
We are signing published jar files with our PGP key
We are using `jarsigner` and CISO servers to sign published jar files
> Switch from GPG to CISO signing solution

- Jenkinsfile
- pom.xml
Switch from jarsigner to pgp for package signing as this is a requirements from Maven central
> refactor: switch package signing from jarsigner to pgp

- .secrets.baseline
- pom.xml
Temprorarily add a direct dependency on `okio` `3.4.0`.
`okio` is a transitive dependency at `3.2.0` from `okhttp` `4.11.0`
Upgrade `okio` to version `3.4.0` because of [CVE-2023-3635](https://www.mend.io/vulnerability-database/CVE-2023-3635).
> build(deps): temporary dependency on okio 3.4.0

- modules/cloudant/src/main/java/com/ibm/cloud/cloudant/features/ChangesFollower.java
- modules/cloudant/src/main/java/com/ibm/cloud/cloudant/features/ChangesOptionsHelper.java
- modules/cloudant/src/main/java/com/ibm/cloud/cloudant/features/ChangesResultSpliterator.java
- modules/cloudant/src/main/java/com/ibm/cloud/cloudant/features/package-info.java
- modules/cloudant/src/test/java/com/ibm/cloud/cloudant/features/ChangesFollowerTest.java
- modules/cloudant/src/test/java/com/ibm/cloud/cloudant/features/ChangesOptionsHelperTest.java
- modules/cloudant/src/test/java/com/ibm/cloud/cloudant/features/ChangesRequestMockClient.java
- modules/cloudant/src/test/java/com/ibm/cloud/cloudant/features/ChangesResultSpliteratorTest.java
- modules/cloudant/src/test/java/com/ibm/cloud/cloudant/features/TestOptions.java
- modules/examples/src/main/java/features/Initialize.java
- modules/examples/src/main/java/features/Start.java
- modules/examples/src/main/java/features/StartAndProcess.java
- modules/examples/src/main/java/features/StartOneOff.java
- modules/examples/src/main/java/features/StartOneOffAndProcess.java
- modules/examples/src/main/java/features/Stop.java
Add changes follower feature.
Users have to call `postChanges` repeatedly and handle various transient errors or disconnects.
The feature adds a helper to automatically paginate the changes feed and return the changes in a stream. It also suppresses transient exceptions and retries (though this can be disabled).
> feat: changes follower

- .github/workflows/test.yml
ci: add Java 21 to matrix
Tests run on Java 11 and 17.
Tests run on Java 11, 17 and 21.
Draft until Java 21 image availability.
>Error: Could not find satisfied version for SemVer '21'.
> ci: add Java 21 to matrix

- .secrets.baseline
- modules/common/src/main/java/com/ibm/cloud/cloudant/security/package-info.java
Remove the `com.ibm.cloud.sdk.core.security` invalid package reference in the Javadoc.
Fixes: i883
> docs: remove invalid package reference

- .github/workflows/docs.yml
- .github/workflows/test.yml
- .secrets.baseline
We are getting deprecation warnings on our CI runs on using outdated actions. This update to fix that.
> ci(chore): update actions checkout and setup-java in github workflows

- modules/examples/pom.xml
Skip `javadoc` generation during build of examples module.
> build: skip javadoc generation for examples module

- pom.xml
Update description with keywords
Fixes: part of s1012
Package metadata update
Add additional keywords for searching.
> chore: update description with keywords

- modules/common/src/main/java/com/ibm/cloud/cloudant/security/CouchDbSessionAuthenticator.java
Rename variable that is clashing with core's `TokenRequestBasedAuthenticatorImmutable` class
Fixes: s1028
> fix: resolve SQ code smell introduced by core 9.22.0

- .github/workflows/static.yml
Update versions of actions in GH pages deployment workflow
Fixes: part of s1192
Deployments fail because of end-of-life dependencies.
Deployments should work.
> ci: docs pages deployment updates

- .github/workflows/docs.yml
- .github/workflows/test.yml
Java 25 updates
Fixes: part of s1232
Test matrix is Temurin 11, 17, 21
Docs build on Temurin 17
Test matrix is Semeru 11, 17, 21, 25
Docs build on Semeru 25
> Update actions for Java 25
